# Generated by Django 4.2.4 on 2024-05-13 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ping_1', '0002_csv_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='csv',
            new_name='csv_1',
        ),
    ]
